spring:
  datasource:
#    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 690780775
    url: jdbc:mysql://localhost:3306/promptDemo?characterEncoding=utf-8&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
